/*
 * wordlist.h
 *
 *  Created on: Jan 12, 2018
 *      Author: ia
 */

#ifndef WORDLIST_H_
#define WORDLIST_H_

#include <stdbool.h>
#include <stdint.h>

const char * bytes_to_words(uint8_t *src, uint8_t len);//, int len);//, const char *words);//, const char *language_name);

const char * const wordlist_electrum[] = {
		 "abbey",
		        "abducts",
		        "ability",
		        "ablaze",
		        "abnormal",
		        "abort",
		        "abrasive",
		        "absorb",
		        "abyss",
		        "academy",
		        "aces",
		        "aching",
		        "acidic",
		        "acoustic",
		        "acquire",
		        "across",
		        "actress",
		        "acumen",
		        "adapt",
		        "addicted",
		        "adept",
		        "adhesive",
		        "adjust",
		        "adopt",
		        "adrenalin",
		        "adult",
		        "adventure",
		        "aerial",
		        "afar",
		        "affair",
		        "afield",
		        "afloat",
		        "afoot",
		        "afraid",
		        "after",
		        "against",
		        "agenda",
		        "aggravate",
		        "agile",
		        "aglow",
		        "agnostic",
		        "agony",
		        "agreed",
		        "ahead",
		        "aided",
		        "ailments",
		        "aimless",
		        "airport",
		        "aisle",
		        "ajar",
		        "akin",
		        "alarms",
		        "album",
		        "alchemy",
		        "alerts",
		        "algebra",
		        "alkaline",
		        "alley",
		        "almost",
		        "aloof",
		        "alpine",
		        "already",
		        "also",
		        "altitude",
		        "alumni",
		        "always",
		        "amaze",
		        "ambush",
		        "amended",
		        "amidst",
		        "ammo",
		        "amnesty",
		        "among",
		        "amply",
		        "amused",
		        "anchor",
		        "android",
		        "anecdote",
		        "angled",
		        "ankle",
		        "annoyed",
		        "answers",
		        "antics",
		        "anvil",
		        "anxiety",
		        "anybody",
		        "apart",
		        "apex",
		        "aphid",
		        "aplomb",
		        "apology",
		        "apply",
		        "apricot",
		        "aptitude",
		        "aquarium",
		        "arbitrary",
		        "archer",
		        "ardent",
		        "arena",
		        "argue",
		        "arises",
		        "army",
		        "around",
		        "arrow",
		        "arsenic",
		        "artistic",
		        "ascend",
		        "ashtray",
		        "aside",
		        "asked",
		        "asleep",
		        "aspire",
		        "assorted",
		        "asylum",
		        "athlete",
		        "atlas",
		        "atom",
		        "atrium",
		        "attire",
		        "auburn",
		        "auctions",
		        "audio",
		        "august",
		        "aunt",
		        "austere",
		        "autumn",
		        "avatar",
		        "avidly",
		        "avoid",
		        "awakened",
		        "awesome",
		        "awful",
		        "awkward",
		        "awning",
		        "awoken",
		        "axes",
		        "axis",
		        "axle",
		        "aztec",
		        "azure",
		        "baby",
		        "bacon",
		        "badge",
		        "baffles",
		        "bagpipe",
		        "bailed",
		        "bakery",
		        "balding",
		        "bamboo",
		        "banjo",
		        "baptism",
		        "basin",
		        "batch",
		        "bawled",
		        "bays",
		        "because",
		        "beer",
		        "befit",
		        "begun",
		        "behind",
		        "being",
		        "below",
		        "bemused",
		        "benches",
		        "berries",
		        "bested",
		        "betting",
		        "bevel",
		        "beware",
		        "beyond",
		        "bias",
		        "bicycle",
		        "bids",
		        "bifocals",
		        "biggest",
		        "bikini",
		        "bimonthly",
		        "binocular",
		        "biology",
		        "biplane",
		        "birth",
		        "biscuit",
		        "bite",
		        "biweekly",
		        "blender",
		        "blip",
		        "bluntly",
		        "boat",
		        "bobsled",
		        "bodies",
		        "bogeys",
		        "boil",
		        "boldly",
		        "bomb",
		        "border",
		        "boss",
		        "both",
		        "bounced",
		        "bovine",
		        "bowling",
		        "boxes",
		        "boyfriend",
		        "broken",
		        "brunt",
		        "bubble",
		        "buckets",
		        "budget",
		        "buffet",
		        "bugs",
		        "building",
		        "bulb",
		        "bumper",
		        "bunch",
		        "business",
		        "butter",
		        "buying",
		        "buzzer",
		        "bygones",
		        "byline",
		        "bypass",
		        "cabin",
		        "cactus",
		        "cadets",
		        "cafe",
		        "cage",
		        "cajun",
		        "cake",
		        "calamity",
		        "camp",
		        "candy",
		        "casket",
		        "catch",
		        "cause",
		        "cavernous",
		        "cease",
		        "cedar",
		        "ceiling",
		        "cell",
		        "cement",
		        "cent",
		        "certain",
		        "chlorine",
		        "chrome",
		        "cider",
		        "cigar",
		        "cinema",
		        "circle",
		        "cistern",
		        "citadel",
		        "civilian",
		        "claim",
		        "click",
		        "clue",
		        "coal",
		        "cobra",
		        "cocoa",
		        "code",
		        "coexist",
		        "coffee",
		        "cogs",
		        "cohesive",
		        "coils",
		        "colony",
		        "comb",
		        "cool",
		        "copy",
		        "corrode",
		        "costume",
		        "cottage",
		        "cousin",
		        "cowl",
		        "criminal",
		        "cube",
		        "cucumber",
		        "cuddled",
		        "cuffs",
		        "cuisine",
		        "cunning",
		        "cupcake",
		        "custom",
		        "cycling",
		        "cylinder",
		        "cynical",
		        "dabbing",
		        "dads",
		        "daft",
		        "dagger",
		        "daily",
		        "damp",
		        "dangerous",
		        "dapper",
		        "darted",
		        "dash",
		        "dating",
		        "dauntless",
		        "dawn",
		        "daytime",
		        "dazed",
		        "debut",
		        "decay",
		        "dedicated",
		        "deepest",
		        "deftly",
		        "degrees",
		        "dehydrate",
		        "deity",
		        "dejected",
		        "delayed",
		        "demonstrate",
		        "dented",
		        "deodorant",
		        "depth",
		        "desk",
		        "devoid",
		        "dewdrop",
		        "dexterity",
		        "dialect",
		        "dice",
		        "diet",
		        "different",
		        "digit",
		        "dilute",
		        "dime",
		        "dinner",
		        "diode",
		        "diplomat",
		        "directed",
		        "distance",
		        "ditch",
		        "divers",
		        "dizzy",
		        "doctor",
		        "dodge",
		        "does",
		        "dogs",
		        "doing",
		        "dolphin",
		        "domestic",
		        "donuts",
		        "doorway",
		        "dormant",
		        "dosage",
		        "dotted",
		        "double",
		        "dove",
		        "down",
		        "dozen",
		        "dreams",
		        "drinks",
		        "drowning",
		        "drunk",
		        "drying",
		        "dual",
		        "dubbed",
		        "duckling",
		        "dude",
		        "duets",
		        "duke",
		        "dullness",
		        "dummy",
		        "dunes",
		        "duplex",
		        "duration",
		        "dusted",
		        "duties",
		        "dwarf",
		        "dwelt",
		        "dwindling",
		        "dying",
		        "dynamite",
		        "dyslexic",
		        "each",
		        "eagle",
		        "earth",
		        "easy",
		        "eating",
		        "eavesdrop",
		        "eccentric",
		        "echo",
		        "eclipse",
		        "economics",
		        "ecstatic",
		        "eden",
		        "edgy",
		        "edited",
		        "educated",
		        "eels",
		        "efficient",
		        "eggs",
		        "egotistic",
		        "eight",
		        "either",
		        "eject",
		        "elapse",
		        "elbow",
		        "eldest",
		        "eleven",
		        "elite",
		        "elope",
		        "else",
		        "eluded",
		        "emails",
		        "ember",
		        "emerge",
		        "emit",
		        "emotion",
		        "empty",
		        "emulate",
		        "energy",
		        "enforce",
		        "enhanced",
		        "enigma",
		        "enjoy",
		        "enlist",
		        "enmity",
		        "enough",
		        "enraged",
		        "ensign",
		        "entrance",
		        "envy",
		        "epoxy",
		        "equip",
		        "erase",
		        "erected",
		        "erosion",
		        "error",
		        "eskimos",
		        "espionage",
		        "essential",
		        "estate",
		        "etched",
		        "eternal",
		        "ethics",
		        "etiquette",
		        "evaluate",
		        "evenings",
		        "evicted",
		        "evolved",
		        "examine",
		        "excess",
		        "exhale",
		        "exit",
		        "exotic",
		        "exquisite",
		        "extra",
		        "exult",
		        "fabrics",
		        "factual",
		        "fading",
		        "fainted",
		        "faked",
		        "fall",
		        "family",
		        "fancy",
		        "farming",
		        "fatal",
		        "faulty",
		        "fawns",
		        "faxed",
		        "fazed",
		        "feast",
		        "february",
		        "federal",
		        "feel",
		        "feline",
		        "females",
		        "fences",
		        "ferry",
		        "festival",
		        "fetches",
		        "fever",
		        "fewest",
		        "fiat",
		        "fibula",
		        "fictional",
		        "fidget",
		        "fierce",
		        "fifteen",
		        "fight",
		        "films",
		        "firm",
		        "fishing",
		        "fitting",
		        "five",
		        "fixate",
		        "fizzle",
		        "fleet",
		        "flippant",
		        "flying",
		        "foamy",
		        "focus",
		        "foes",
		        "foggy",
		        "foiled",
		        "folding",
		        "fonts",
		        "foolish",
		        "fossil",
		        "fountain",
		        "fowls",
		        "foxes",
		        "foyer",
		        "framed",
		        "friendly",
		        "frown",
		        "fruit",
		        "frying",
		        "fudge",
		        "fuel",
		        "fugitive",
		        "fully",
		        "fuming",
		        "fungal",
		        "furnished",
		        "fuselage",
		        "future",
		        "fuzzy",
		        "gables",
		        "gadget",
		        "gags",
		        "gained",
		        "galaxy",
		        "gambit",
		        "gang",
		        "gasp",
		        "gather",
		        "gauze",
		        "gave",
		        "gawk",
		        "gaze",
		        "gearbox",
		        "gecko",
		        "geek",
		        "gels",
		        "gemstone",
		        "general",
		        "geometry",
		        "germs",
		        "gesture",
		        "getting",
		        "geyser",
		        "ghetto",
		        "ghost",
		        "giant",
		        "giddy",
		        "gifts",
		        "gigantic",
		        "gills",
		        "gimmick",
		        "ginger",
		        "girth",
		        "giving",
		        "glass",
		        "gleeful",
		        "glide",
		        "gnaw",
		        "gnome",
		        "goat",
		        "goblet",
		        "godfather",
		        "goes",
		        "goggles",
		        "going",
		        "goldfish",
		        "gone",
		        "goodbye",
		        "gopher",
		        "gorilla",
		        "gossip",
		        "gotten",
		        "gourmet",
		        "governing",
		        "gown",
		        "greater",
		        "grunt",
		        "guarded",
		        "guest",
		        "guide",
		        "gulp",
		        "gumball",
		        "guru",
		        "gusts",
		        "gutter",
		        "guys",
		        "gymnast",
		        "gypsy",
		        "gyrate",
		        "habitat",
		        "hacksaw",
		        "haggled",
		        "hairy",
		        "hamburger",
		        "happens",
		        "hashing",
		        "hatchet",
		        "haunted",
		        "having",
		        "hawk",
		        "haystack",
		        "hazard",
		        "hectare",
		        "hedgehog",
		        "heels",
		        "hefty",
		        "height",
		        "hemlock",
		        "hence",
		        "heron",
		        "hesitate",
		        "hexagon",
		        "hickory",
		        "hiding",
		        "highway",
		        "hijack",
		        "hiker",
		        "hills",
		        "himself",
		        "hinder",
		        "hippo",
		        "hire",
		        "history",
		        "hitched",
		        "hive",
		        "hoax",
		        "hobby",
		        "hockey",
		        "hoisting",
		        "hold",
		        "honked",
		        "hookup",
		        "hope",
		        "hornet",
		        "hospital",
		        "hotel",
		        "hounded",
		        "hover",
		        "howls",
		        "hubcaps",
		        "huddle",
		        "huge",
		        "hull",
		        "humid",
		        "hunter",
		        "hurried",
		        "husband",
		        "huts",
		        "hybrid",
		        "hydrogen",
		        "hyper",
		        "iceberg",
		        "icing",
		        "icon",
		        "identity",
		        "idiom",
		        "idled",
		        "idols",
		        "igloo",
		        "ignore",
		        "iguana",
		        "illness",
		        "imagine",
		        "imbalance",
		        "imitate",
		        "impel",
		        "inactive",
		        "inbound",
		        "incur",
		        "industrial",
		        "inexact",
		        "inflamed",
		        "ingested",
		        "initiate",
		        "injury",
		        "inkling",
		        "inline",
		        "inmate",
		        "innocent",
		        "inorganic",
		        "input",
		        "inquest",
		        "inroads",
		        "insult",
		        "intended",
		        "inundate",
		        "invoke",
		        "inwardly",
		        "ionic",
		        "irate",
		        "iris",
		        "irony",
		        "irritate",
		        "island",
		        "isolated",
		        "issued",
		        "italics",
		        "itches",
		        "items",
		        "itinerary",
		        "itself",
		        "ivory",
		        "jabbed",
		        "jackets",
		        "jaded",
		        "jagged",
		        "jailed",
		        "jamming",
		        "january",
		        "jargon",
		        "jaunt",
		        "javelin",
		        "jaws",
		        "jazz",
		        "jeans",
		        "jeers",
		        "jellyfish",
		        "jeopardy",
		        "jerseys",
		        "jester",
		        "jetting",
		        "jewels",
		        "jigsaw",
		        "jingle",
		        "jittery",
		        "jive",
		        "jobs",
		        "jockey",
		        "jogger",
		        "joining",
		        "joking",
		        "jolted",
		        "jostle",
		        "journal",
		        "joyous",
		        "jubilee",
		        "judge",
		        "juggled",
		        "juicy",
		        "jukebox",
		        "july",
		        "jump",
		        "junk",
		        "jury",
		        "justice",
		        "juvenile",
		        "kangaroo",
		        "karate",
		        "keep",
		        "kennel",
		        "kept",
		        "kernels",
		        "kettle",
		        "keyboard",
		        "kickoff",
		        "kidneys",
		        "king",
		        "kiosk",
		        "kisses",
		        "kitchens",
		        "kiwi",
		        "knapsack",
		        "knee",
		        "knife",
		        "knowledge",
		        "knuckle",
		        "koala",
		        "laboratory",
		        "ladder",
		        "lagoon",
		        "lair",
		        "lakes",
		        "lamb",
		        "language",
		        "laptop",
		        "large",
		        "last",
		        "later",
		        "launching",
		        "lava",
		        "lawsuit",
		        "layout",
		        "lazy",
		        "lectures",
		        "ledge",
		        "leech",
		        "left",
		        "legion",
		        "leisure",
		        "lemon",
		        "lending",
		        "leopard",
		        "lesson",
		        "lettuce",
		        "lexicon",
		        "liar",
		        "library",
		        "licks",
		        "lids",
		        "lied",
		        "lifestyle",
		        "light",
		        "likewise",
		        "lilac",
		        "limits",
		        "linen",
		        "lion",
		        "lipstick",
		        "liquid",
		        "listen",
		        "lively",
		        "loaded",
		        "lobster",
		        "locker",
		        "lodge",
		        "lofty",
		        "logic",
		        "loincloth",
		        "long",
		        "looking",
		        "lopped",
		        "lordship",
		        "losing",
		        "lottery",
		        "loudly",
		        "love",
		        "lower",
		        "loyal",
		        "lucky",
		        "luggage",
		        "lukewarm",
		        "lullaby",
		        "lumber",
		        "lunar",
		        "lurk",
		        "lush",
		        "luxury",
		        "lymph",
		        "lynx",
		        "lyrics",
		        "macro",
		        "madness",
		        "magically",
		        "mailed",
		        "major",
		        "makeup",
		        "malady",
		        "mammal",
		        "maps",
		        "masterful",
		        "match",
		        "maul",
		        "maverick",
		        "maximum",
		        "mayor",
		        "maze",
		        "meant",
		        "mechanic",
		        "medicate",
		        "meeting",
		        "megabyte",
		        "melting",
		        "memoir",
		        "menu",
		        "merger",
		        "mesh",
		        "metro",
		        "mews",
		        "mice",
		        "midst",
		        "mighty",
		        "mime",
		        "mirror",
		        "misery",
		        "mittens",
		        "mixture",
		        "moat",
		        "mobile",
		        "mocked",
		        "mohawk",
		        "moisture",
		        "molten",
		        "moment",
		        "money",
		        "moon",
		        "mops",
		        "morsel",
		        "mostly",
		        "motherly",
		        "mouth",
		        "movement",
		        "mowing",
		        "much",
		        "muddy",
		        "muffin",
		        "mugged",
		        "mullet",
		        "mumble",
		        "mundane",
		        "muppet",
		        "mural",
		        "musical",
		        "muzzle",
		        "myriad",
		        "mystery",
		        "myth",
		        "nabbing",
		        "nagged",
		        "nail",
		        "names",
		        "nanny",
		        "napkin",
		        "narrate",
		        "nasty",
		        "natural",
		        "nautical",
		        "navy",
		        "nearby",
		        "necklace",
		        "needed",
		        "negative",
		        "neither",
		        "neon",
		        "nephew",
		        "nerves",
		        "nestle",
		        "network",
		        "neutral",
		        "never",
		        "newt",
		        "nexus",
		        "nibs",
		        "niche",
		        "niece",
		        "nifty",
		        "nightly",
		        "nimbly",
		        "nineteen",
		        "nirvana",
		        "nitrogen",
		        "nobody",
		        "nocturnal",
		        "nodes",
		        "noises",
		        "nomad",
		        "noodles",
		        "northern",
		        "nostril",
		        "noted",
		        "nouns",
		        "novelty",
		        "nowhere",
		        "nozzle",
		        "nuance",
		        "nucleus",
		        "nudged",
		        "nugget",
		        "nuisance",
		        "null",
		        "number",
		        "nuns",
		        "nurse",
		        "nutshell",
		        "nylon",
		        "oaks",
		        "oars",
		        "oasis",
		        "oatmeal",
		        "obedient",
		        "object",
		        "obliged",
		        "obnoxious",
		        "observant",
		        "obtains",
		        "obvious",
		        "occur",
		        "ocean",
		        "october",
		        "odds",
		        "odometer",
		        "offend",
		        "often",
		        "oilfield",
		        "ointment",
		        "okay",
		        "older",
		        "olive",
		        "olympics",
		        "omega",
		        "omission",
		        "omnibus",
		        "onboard",
		        "oncoming",
		        "oneself",
		        "ongoing",
		        "onion",
		        "online",
		        "onslaught",
		        "onto",
		        "onward",
		        "oozed",
		        "opacity",
		        "opened",
		        "opposite",
		        "optical",
		        "opus",
		        "orange",
		        "orbit",
		        "orchid",
		        "orders",
		        "organs",
		        "origin",
		        "ornament",
		        "orphans",
		        "oscar",
		        "ostrich",
		        "otherwise",
		        "otter",
		        "ouch",
		        "ought",
		        "ounce",
		        "ourselves",
		        "oust",
		        "outbreak",
		        "oval",
		        "oven",
		        "owed",
		        "owls",
		        "owner",
		        "oxidant",
		        "oxygen",
		        "oyster",
		        "ozone",
		        "pact",
		        "paddles",
		        "pager",
		        "pairing",
		        "palace",
		        "pamphlet",
		        "pancakes",
		        "paper",
		        "paradise",
		        "pastry",
		        "patio",
		        "pause",
		        "pavements",
		        "pawnshop",
		        "payment",
		        "peaches",
		        "pebbles",
		        "peculiar",
		        "pedantic",
		        "peeled",
		        "pegs",
		        "pelican",
		        "pencil",
		        "people",
		        "pepper",
		        "perfect",
		        "pests",
		        "petals",
		        "phase",
		        "pheasants",
		        "phone",
		        "phrases",
		        "physics",
		        "piano",
		        "picked",
		        "pierce",
		        "pigment",
		        "piloted",
		        "pimple",
		        "pinched",
		        "pioneer",
		        "pipeline",
		        "pirate",
		        "pistons",
		        "pitched",
		        "pivot",
		        "pixels",
		        "pizza",
		        "playful",
		        "pledge",
		        "pliers",
		        "plotting",
		        "plus",
		        "plywood",
		        "poaching",
		        "pockets",
		        "podcast",
		        "poetry",
		        "point",
		        "poker",
		        "polar",
		        "ponies",
		        "pool",
		        "popular",
		        "portents",
		        "possible",
		        "potato",
		        "pouch",
		        "poverty",
		        "powder",
		        "pram",
		        "present",
		        "pride",
		        "problems",
		        "pruned",
		        "prying",
		        "psychic",
		        "public",
		        "puck",
		        "puddle",
		        "puffin",
		        "pulp",
		        "pumpkins",
		        "punch",
		        "puppy",
		        "purged",
		        "push",
		        "putty",
		        "puzzled",
		        "pylons",
		        "pyramid",
		        "python",
		        "queen",
		        "quick",
		        "quote",
		        "rabbits",
		        "racetrack",
		        "radar",
		        "rafts",
		        "rage",
		        "railway",
		        "raking",
		        "rally",
		        "ramped",
		        "randomly",
		        "rapid",
		        "rarest",
		        "rash",
		        "rated",
		        "ravine",
		        "rays",
		        "razor",
		        "react",
		        "rebel",
		        "recipe",
		        "reduce",
		        "reef",
		        "refer",
		        "regular",
		        "reheat",
		        "reinvest",
		        "rejoices",
		        "rekindle",
		        "relic",
		        "remedy",
		        "renting",
		        "reorder",
		        "repent",
		        "request",
		        "reruns",
		        "rest",
		        "return",
		        "reunion",
		        "revamp",
		        "rewind",
		        "rhino",
		        "rhythm",
		        "ribbon",
		        "richly",
		        "ridges",
		        "rift",
		        "rigid",
		        "rims",
		        "ringing",
		        "riots",
		        "ripped",
		        "rising",
		        "ritual",
		        "river",
		        "roared",
		        "robot",
		        "rockets",
		        "rodent",
		        "rogue",
		        "roles",
		        "romance",
		        "roomy",
		        "roped",
		        "roster",
		        "rotate",
		        "rounded",
		        "rover",
		        "rowboat",
		        "royal",
		        "ruby",
		        "rudely",
		        "ruffled",
		        "rugged",
		        "ruined",
		        "ruling",
		        "rumble",
		        "runway",
		        "rural",
		        "rustled",
		        "ruthless",
		        "sabotage",
		        "sack",
		        "sadness",
		        "safety",
		        "saga",
		        "sailor",
		        "sake",
		        "salads",
		        "sample",
		        "sanity",
		        "sapling",
		        "sarcasm",
		        "sash",
		        "satin",
		        "saucepan",
		        "saved",
		        "sawmill",
		        "saxophone",
		        "sayings",
		        "scamper",
		        "scenic",
		        "school",
		        "science",
		        "scoop",
		        "scrub",
		        "scuba",
		        "seasons",
		        "second",
		        "sedan",
		        "seeded",
		        "segments",
		        "seismic",
		        "selfish",
		        "semifinal",
		        "sensible",
		        "september",
		        "sequence",
		        "serving",
		        "session",
		        "setup",
		        "seventh",
		        "sewage",
		        "shackles",
		        "shelter",
		        "shipped",
		        "shocking",
		        "shrugged",
		        "shuffled",
		        "shyness",
		        "siblings",
		        "sickness",
		        "sidekick",
		        "sieve",
		        "sifting",
		        "sighting",
		        "silk",
		        "simplest",
		        "sincerely",
		        "sipped",
		        "siren",
		        "situated",
		        "sixteen",
		        "sizes",
		        "skater",
		        "skew",
		        "skirting",
		        "skulls",
		        "skydive",
		        "slackens",
		        "sleepless",
		        "slid",
		        "slower",
		        "slug",
		        "smash",
		        "smelting",
		        "smidgen",
		        "smog",
		        "smuggled",
		        "snake",
		        "sneeze",
		        "sniff",
		        "snout",
		        "snug",
		        "soapy",
		        "sober",
		        "soccer",
		        "soda",
		        "software",
		        "soggy",
		        "soil",
		        "solved",
		        "somewhere",
		        "sonic",
		        "soothe",
		        "soprano",
		        "sorry",
		        "southern",
		        "sovereign",
		        "sowed",
		        "soya",
		        "space",
		        "speedy",
		        "sphere",
		        "spiders",
		        "splendid",
		        "spout",
		        "sprig",
		        "spud",
		        "spying",
		        "square",
		        "stacking",
		        "stellar",
		        "stick",
		        "stockpile",
		        "strained",
		        "stunning",
		        "stylishly",
		        "subtly",
		        "succeed",
		        "suddenly",
		        "suede",
		        "suffice",
		        "sugar",
		        "suitcase",
		        "sulking",
		        "summon",
		        "sunken",
		        "superior",
		        "surfer",
		        "sushi",
		        "suture",
		        "swagger",
		        "swept",
		        "swiftly",
		        "sword",
		        "swung",
		        "syllabus",
		        "symptoms",
		        "syndrome",
		        "syringe",
		        "system",
		        "taboo",
		        "tacit",
		        "tadpoles",
		        "tagged",
		        "tail",
		        "taken",
		        "talent",
		        "tamper",
		        "tanks",
		        "tapestry",
		        "tarnished",
		        "tasked",
		        "tattoo",
		        "taunts",
		        "tavern",
		        "tawny",
		        "taxi",
		        "teardrop",
		        "technical",
		        "tedious",
		        "teeming",
		        "tell",
		        "template",
		        "tender",
		        "tepid",
		        "tequila",
		        "terminal",
		        "testing",
		        "tether",
		        "textbook",
		        "thaw",
		        "theatrics",
		        "thirsty",
		        "thorn",
		        "threaten",
		        "thumbs",
		        "thwart",
		        "ticket",
		        "tidy",
		        "tiers",
		        "tiger",
		        "tilt",
		        "timber",
		        "tinted",
		        "tipsy",
		        "tirade",
		        "tissue",
		        "titans",
		        "toaster",
		        "tobacco",
		        "today",
		        "toenail",
		        "toffee",
		        "together",
		        "toilet",
		        "token",
		        "tolerant",
		        "tomorrow",
		        "tonic",
		        "toolbox",
		        "topic",
		        "torch",
		        "tossed",
		        "total",
		        "touchy",
		        "towel",
		        "toxic",
		        "toyed",
		        "trash",
		        "trendy",
		        "tribal",
		        "trolling",
		        "truth",
		        "trying",
		        "tsunami",
		        "tubes",
		        "tucks",
		        "tudor",
		        "tuesday",
		        "tufts",
		        "tugs",
		        "tuition",
		        "tulips",
		        "tumbling",
		        "tunnel",
		        "turnip",
		        "tusks",
		        "tutor",
		        "tuxedo",
		        "twang",
		        "tweezers",
		        "twice",
		        "twofold",
		        "tycoon",
		        "typist",
		        "tyrant",
		        "ugly",
		        "ulcers",
		        "ultimate",
		        "umbrella",
		        "umpire",
		        "unafraid",
		        "unbending",
		        "uncle",
		        "under",
		        "uneven",
		        "unfit",
		        "ungainly",
		        "unhappy",
		        "union",
		        "unjustly",
		        "unknown",
		        "unlikely",
		        "unmask",
		        "unnoticed",
		        "unopened",
		        "unplugs",
		        "unquoted",
		        "unrest",
		        "unsafe",
		        "until",
		        "unusual",
		        "unveil",
		        "unwind",
		        "unzip",
		        "upbeat",
		        "upcoming",
		        "update",
		        "upgrade",
		        "uphill",
		        "upkeep",
		        "upload",
		        "upon",
		        "upper",
		        "upright",
		        "upstairs",
		        "uptight",
		        "upwards",
		        "urban",
		        "urchins",
		        "urgent",
		        "usage",
		        "useful",
		        "usher",
		        "using",
		        "usual",
		        "utensils",
		        "utility",
		        "utmost",
		        "utopia",
		        "uttered",
		        "vacation",
		        "vague",
		        "vain",
		        "value",
		        "vampire",
		        "vane",
		        "vapidly",
		        "vary",
		        "vastness",
		        "vats",
		        "vaults",
		        "vector",
		        "veered",
		        "vegan",
		        "vehicle",
		        "vein",
		        "velvet",
		        "venomous",
		        "verification",
		        "vessel",
		        "veteran",
		        "vexed",
		        "vials",
		        "vibrate",
		        "victim",
		        "video",
		        "viewpoint",
		        "vigilant",
		        "viking",
		        "village",
		        "vinegar",
		        "violin",
		        "vipers",
		        "virtual",
		        "visited",
		        "vitals",
		        "vivid",
		        "vixen",
		        "vocal",
		        "vogue",
		        "voice",
		        "volcano",
		        "vortex",
		        "voted",
		        "voucher",
		        "vowels",
		        "voyage",
		        "vulture",
		        "wade",
		        "waffle",
		        "wagtail",
		        "waist",
		        "waking",
		        "wallets",
		        "wanted",
		        "warped",
		        "washing",
		        "water",
		        "waveform",
		        "waxing",
		        "wayside",
		        "weavers",
		        "website",
		        "wedge",
		        "weekday",
		        "weird",
		        "welders",
		        "went",
		        "wept",
		        "were",
		        "western",
		        "wetsuit",
		        "whale",
		        "when",
		        "whipped",
		        "whole",
		        "wickets",
		        "width",
		        "wield",
		        "wife",
		        "wiggle",
		        "wildly",
		        "winter",
		        "wipeout",
		        "wiring",
		        "wise",
		        "withdrawn",
		        "wives",
		        "wizard",
		        "wobbly",
		        "woes",
		        "woken",
		        "wolf",
		        "womanly",
		        "wonders",
		        "woozy",
		        "worry",
		        "wounded",
		        "woven",
		        "wrap",
		        "wrist",
		        "wrong",
		        "yacht",
		        "yahoo",
		        "yanks",
		        "yard",
		        "yawning",
		        "yearbook",
		        "yellow",
		        "yesterday",
		        "yeti",
		        "yields",
		        "yodel",
		        "yoga",
		        "younger",
		        "yoyo",
		        "zapped",
		        "zeal",
		        "zebra",
		        "zero",
		        "zesty",
		        "zigzags",
		        "zinger",
		        "zippers",
		        "zodiac",
		        "zombie",
		        "zones",
		        "zoom"

};
/*
 *
 * 	Not sure if we are ever going to use this wordlist,
 * 	but I will let it here,please somebody delete it
 *
 *
const char * const wordlist_electrum[] = {
"like", "just", "love", "know", "never", "want", "time", "out", "there",
"make", "look", "eye", "down", "only", "think", "heart", "back", "then",
"into", "about", "more", "away", "still", "them", "take", "thing", "even",
"through", "long", "always", "world", "too", "friend", "tell", "try",
"hand", "thought", "over", "here", "other", "need", "smile", "again",
"much", "cry", "been", "night", "ever", "little", "said", "end", "some",
"those", "around", "mind", "people", "girl", "leave", "dream", "left",
"turn", "myself", "give", "nothing", "really", "off", "before",
"something", "find", "walk", "wish", "good", "once", "place", "ask",
"stop", "keep", "watch", "seem", "everything", "wait", "got", "yet",
"made", "remember", "start", "alone", "run", "hope", "maybe", "believe",
"body", "hate", "after", "close", "talk", "stand", "own", "each", "hurt",
"help", "home", "god", "soul", "new", "many", "two", "inside", "should",
"true", "first", "fear", "mean", "better", "play", "another", "gone",
"change", "use", "wonder", "someone", "hair", "cold", "open", "best",
"any", "behind", "happen", "water", "dark", "laugh", "stay", "forever",
"name", "work", "show", "sky", "break", "came", "deep", "door", "put",
"black", "together", "upon", "happy", "such", "great", "white", "matter",
"fill", "past", "please", "burn", "cause", "enough", "touch", "moment",
"soon", "voice", "scream", "anything", "stare", "sound", "red", "everyone",
"hide", "kiss", "truth", "death", "beautiful", "mine", "blood", "broken",
"very", "pass", "next", "forget", "tree", "wrong", "air", "mother",
"understand", "lip", "hit", "wall", "memory", "sleep", "free", "high",
"realize", "school", "might", "skin", "sweet", "perfect", "blue", "kill",
"breath", "dance", "against", "fly", "between", "grow", "strong", "under",
"listen", "bring", "sometimes", "speak", "pull", "person", "become",
"family", "begin", "ground", "real", "small", "father", "sure", "feet",
"rest", "young", "finally", "land", "across", "today", "different", "guy",
"line", "fire", "reason", "reach", "second", "slowly", "write", "eat",
"smell", "mouth", "step", "learn", "three", "floor", "promise", "breathe",
"darkness", "push", "earth", "guess", "save", "song", "above", "along",
"both", "color", "house", "almost", "sorry", "anymore", "brother", "okay",
"dear", "game", "fade", "already", "apart", "warm", "beauty", "heard",
"notice", "question", "shine", "began", "piece", "whole", "shadow",
"secret", "street", "within", "finger", "point", "morning", "whisper",
"child", "moon", "green", "story", "glass", "kid", "silence", "since",
"soft", "yourself", "empty", "shall", "angel", "answer", "baby", "bright",
"dad", "path", "worry", "hour", "drop", "follow", "power", "war", "half",
"flow", "heaven", "act", "chance", "fact", "least", "tired", "children",
"near", "quite", "afraid", "rise", "sea", "taste", "window", "cover",
"nice", "trust", "lot", "sad", "cool", "force", "peace", "return", "blind",
"easy", "ready", "roll", "rose", "drive", "held", "music", "beneath",
"hang", "mom", "paint", "emotion", "quiet", "clear", "cloud", "few",
"pretty", "bird", "outside", "paper", "picture", "front", "rock", "simple",
"anyone", "meant", "reality", "road", "sense", "waste", "bit", "leaf",
"thank", "happiness", "meet", "men", "smoke", "truly", "decide", "self",
"age", "book", "form", "alive", "carry", "escape", "damn", "instead",
"able", "ice", "minute", "throw", "catch", "leg", "ring", "course",
"goodbye", "lead", "poem", "sick", "corner", "desire", "known", "problem",
"remind", "shoulder", "suppose", "toward", "wave", "drink", "jump",
"woman", "pretend", "sister", "week", "human", "joy", "crack", "grey",
"pray", "surprise", "dry", "knee", "less", "search", "bleed", "caught",
"clean", "embrace", "future", "king", "son", "sorrow", "chest", "hug",
"remain", "sat", "worth", "blow", "daddy", "final", "parent", "tight",
"also", "create", "lonely", "safe", "cross", "dress", "evil", "silent",
"bone", "fate", "perhaps", "anger", "class", "scar", "snow", "tiny",
"tonight", "continue", "control", "dog", "edge", "mirror", "month",
"suddenly", "comfort", "given", "loud", "quickly", "gaze", "plan", "rush",
"stone", "town", "battle", "ignore", "spirit", "stood", "stupid", "yours",
"brown", "build", "dust", "hey", "kept", "pay", "phone", "twist",
"although", "ball", "beyond", "hidden", "nose", "taken", "fail", "float",
"pure", "somehow", "wash", "wrap", "angry", "cheek", "creature",
"forgotten", "heat", "rip", "single", "space", "special", "weak",
"whatever", "yell", "anyway", "blame", "job", "choose", "country", "curse",
"drift", "echo", "figure", "grew", "laughter", "neck", "suffer", "worse",
"yeah", "disappear", "foot", "forward", "knife", "mess", "somewhere",
"stomach", "storm", "beg", "idea", "lift", "offer", "breeze", "field",
"five", "often", "simply", "stuck", "win", "allow", "confuse", "enjoy",
"except", "flower", "seek", "strength", "calm", "grin", "gun", "heavy",
"hill", "large", "ocean", "shoe", "sigh", "straight", "summer", "tongue",
"accept", "crazy", "everyday", "exist", "grass", "mistake", "sent", "shut",
"surround", "table", "ache", "brain", "destroy", "heal", "nature", "shout",
"sign", "stain", "choice", "doubt", "glance", "glow", "mountain", "queen",
"stranger", "throat", "tomorrow", "city", "either", "fish", "flame",
"rather", "shape", "spin", "spread", "ash", "distance", "finish", "image",
"imagine", "important", "nobody", "shatter", "warmth", "became", "feed",
"flesh", "funny", "lust", "shirt", "trouble", "yellow", "attention",
"bare", "bite", "money", "protect", "amaze", "appear", "born", "choke",
"completely", "daughter", "fresh", "friendship", "gentle", "probably",
"six", "deserve", "expect", "grab", "middle", "nightmare", "river",
"thousand", "weight", "worst", "wound", "barely", "bottle", "cream",
"regret", "relationship", "stick", "test", "crush", "endless", "fault",
"itself", "rule", "spill", "art", "circle", "join", "kick", "mask",
"master", "passion", "quick", "raise", "smooth", "unless", "wander",
"actually", "broke", "chair", "deal", "favorite", "gift", "note", "number",
"sweat", "box", "chill", "clothes", "lady", "mark", "park", "poor",
"sadness", "tie", "animal", "belong", "brush", "consume", "dawn", "forest",
"innocent", "pen", "pride", "stream", "thick", "clay", "complete", "count",
"draw", "faith", "press", "silver", "struggle", "surface", "taught",
"teach", "wet", "bless", "chase", "climb", "enter", "letter", "melt",
"metal", "movie", "stretch", "swing", "vision", "wife", "beside", "crash",
"forgot", "guide", "haunt", "joke", "knock", "plant", "pour", "prove",
"reveal", "steal", "stuff", "trip", "wood", "wrist", "bother", "bottom",
"crawl", "crowd", "fix", "forgive", "frown", "grace", "loose", "lucky",
"party", "release", "surely", "survive", "teacher", "gently", "grip",
"speed", "suicide", "travel", "treat", "vein", "written", "cage", "chain",
"conversation", "date", "enemy", "however", "interest", "million", "page",
"pink", "proud", "sway", "themselves", "winter", "church", "cruel", "cup",
"demon", "experience", "freedom", "pair", "pop", "purpose", "respect",
"shoot", "softly", "state", "strange", "bar", "birth", "curl", "dirt",
"excuse", "lord", "lovely", "monster", "order", "pack", "pants", "pool",
"scene", "seven", "shame", "slide", "ugly", "among", "blade", "blonde",
"closet", "creek", "deny", "drug", "eternity", "gain", "grade", "handle",
"key", "linger", "pale", "prepare", "swallow", "swim", "tremble", "wheel",
"won", "cast", "cigarette", "claim", "college", "direction", "dirty",
"gather", "ghost", "hundred", "loss", "lung", "orange", "present", "swear",
"swirl", "twice", "wild", "bitter", "blanket", "doctor", "everywhere",
"flash", "grown", "knowledge", "numb", "pressure", "radio", "repeat",
"ruin", "spend", "unknown", "buy", "clock", "devil", "early", "false",
"fantasy", "pound", "precious", "refuse", "sheet", "teeth", "welcome",
"add", "ahead", "block", "bury", "caress", "content", "depth", "despite",
"distant", "marry", "purple", "threw", "whenever", "bomb", "dull",
"easily", "grasp", "hospital", "innocence", "normal", "receive", "reply",
"rhyme", "shade", "someday", "sword", "toe", "visit", "asleep", "bought",
"center", "consider", "flat", "hero", "history", "ink", "insane", "muscle",
"mystery", "pocket", "reflection", "shove", "silently", "smart", "soldier",
"spot", "stress", "train", "type", "view", "whether", "bus", "energy",
"explain", "holy", "hunger", "inch", "magic", "mix", "noise", "nowhere",
"prayer", "presence", "shock", "snap", "spider", "study", "thunder",
"trail", "admit", "agree", "bag", "bang", "bound", "butterfly", "cute",
"exactly", "explode", "familiar", "fold", "further", "pierce", "reflect",
"scent", "selfish", "sharp", "sink", "spring", "stumble", "universe",
"weep", "women", "wonderful", "action", "ancient", "attempt", "avoid",
"birthday", "branch", "chocolate", "core", "depress", "drunk",
"especially", "focus", "fruit", "honest", "match", "palm", "perfectly",
"pillow", "pity", "poison", "roar", "shift", "slightly", "thump", "truck",
"tune", "twenty", "unable", "wipe", "wrote", "coat", "constant", "dinner",
"drove", "egg", "eternal", "flight", "flood", "frame", "freak", "gasp",
"glad", "hollow", "motion", "peer", "plastic", "root", "screen", "season",
"sting", "strike", "team", "unlike", "victim", "volume", "warn", "weird",
"attack", "await", "awake", "built", "charm", "crave", "despair", "fought",
"grant", "grief", "horse", "limit", "message", "ripple", "sanity",
"scatter", "serve", "split", "string", "trick", "annoy", "blur", "boat",
"brave", "clearly", "cling", "connect", "fist", "forth", "imagination",
"iron", "jock", "judge", "lesson", "milk", "misery", "nail", "naked",
"ourselves", "poet", "possible", "princess", "sail", "size", "snake",
"society", "stroke", "torture", "toss", "trace", "wise", "bloom", "bullet",
"cell", "check", "cost", "darling", "during", "footstep", "fragile",
"hallway", "hardly", "horizon", "invisible", "journey", "midnight", "mud",
"nod", "pause", "relax", "shiver", "sudden", "value", "youth", "abuse",
"admire", "blink", "breast", "bruise", "constantly", "couple", "creep",
"curve", "difference", "dumb", "emptiness", "gotta", "honor", "plain",
"planet", "recall", "rub", "ship", "slam", "soar", "somebody", "tightly",
"weather", "adore", "approach", "bond", "bread", "burst", "candle",
"coffee", "cousin", "crime", "desert", "flutter", "frozen", "grand",
"heel", "hello", "language", "level", "movement", "pleasure", "powerful",
"random", "rhythm", "settle", "silly", "slap", "sort", "spoken", "steel",
"threaten", "tumble", "upset", "aside", "awkward", "bee", "blank", "board",
"button", "card", "carefully", "complain", "crap", "deeply", "discover",
"drag", "dread", "effort", "entire", "fairy", "giant", "gotten", "greet",
"illusion", "jeans", "leap", "liquid", "march", "mend", "nervous", "nine",
"replace", "rope", "spine", "stole", "terror", "accident", "apple",
"balance", "boom", "childhood", "collect", "demand", "depression",
"eventually", "faint", "glare", "goal", "group", "honey", "kitchen",
"laid", "limb", "machine", "mere", "mold", "murder", "nerve", "painful",
"poetry", "prince", "rabbit", "shelter", "shore", "shower", "soothe",
"stair", "steady", "sunlight", "tangle", "tease", "treasure", "uncle",
"begun", "bliss", "canvas", "cheer", "claw", "clutch", "commit", "crimson",
"crystal", "delight", "doll", "existence", "express", "fog", "football",
"gay", "goose", "guard", "hatred", "illuminate", "mass", "math", "mourn",
"rich", "rough", "skip", "stir", "student", "style", "support", "thorn",
"tough", "yard", "yearn", "yesterday", "advice", "appreciate", "autumn",
"bank", "beam", "bowl", "capture", "carve", "collapse", "confusion",
"creation", "dove", "feather", "girlfriend", "glory", "government",
"harsh", "hop", "inner", "loser", "moonlight", "neighbor", "neither",
"peach", "pig", "praise", "screw", "shield", "shimmer", "sneak", "stab",
"subject", "throughout", "thrown", "tower", "twirl", "wow", "army",
"arrive", "bathroom", "bump", "cease", "cookie", "couch", "courage", "dim",
"guilt", "howl", "hum", "husband", "insult", "led", "lunch", "mock",
"mostly", "natural", "nearly", "needle", "nerd", "peaceful", "perfection",
"pile", "price", "remove", "roam", "sanctuary", "serious", "shiny",
"shook", "sob", "stolen", "tap", "vain", "void", "warrior", "wrinkle",
"affection", "apologize", "blossom", "bounce", "bridge", "cheap",
"crumble", "decision", "descend", "desperately", "dig", "dot", "flip",
"frighten", "heartbeat", "huge", "lazy", "lick", "odd", "opinion",
"process", "puzzle", "quietly", "retreat", "score", "sentence", "separate",
"situation", "skill", "soak", "square", "stray", "taint", "task", "tide",
"underneath", "veil", "whistle", "anywhere", "bedroom", "bid", "bloody",
"burden", "careful", "compare", "concern", "curtain", "decay", "defeat",
"describe", "double", "dreamer", "driver", "dwell", "evening", "flare",
"flicker", "grandma", "guitar", "harm", "horrible", "hungry", "indeed",
"lace", "melody", "monkey", "nation", "object", "obviously", "rainbow",
"salt", "scratch", "shown", "shy", "stage", "stun", "third", "tickle",
"useless", "weakness", "worship", "worthless", "afternoon", "beard",
"boyfriend", "bubble", "busy", "certain", "chin", "concrete", "desk",
"diamond", "doom", "drawn", "due", "felicity", "freeze", "frost", "garden",
"glide", "harmony", "hopefully", "hunt", "jealous", "lightning", "mama",
"mercy", "peel", "physical", "position", "pulse", "punch", "quit", "rant",
"respond", "salty", "sane", "satisfy", "savior", "sheep", "slept",
"social", "sport", "tuck", "utter", "valley", "wolf", "aim", "alas",
"alter", "arrow", "awaken", "beaten", "belief", "brand", "ceiling",
"cheese", "clue", "confidence", "connection", "daily", "disguise", "eager",
"erase", "essence", "everytime", "expression", "fan", "flag", "flirt",
"foul", "fur", "giggle", "glorious", "ignorance", "law", "lifeless",
"measure", "mighty", "muse", "north", "opposite", "paradise", "patience",
"patient", "pencil", "petal", "plate", "ponder", "possibly", "practice",
"slice", "spell", "stock", "strife", "strip", "suffocate", "suit",
"tender", "tool", "trade", "velvet", "verse", "waist", "witch", "aunt",
"bench", "bold", "cap", "certainly", "click", "companion", "creator",
"dart", "delicate", "determine", "dish", "dragon", "drama", "drum", "dude",
"everybody", "feast", "forehead", "former", "fright", "fully", "gas",
"hook", "hurl", "invite", "juice", "manage", "moral", "possess", "raw",
"rebel", "royal", "scale", "scary", "several", "slight", "stubborn",
"swell", "talent", "tea", "terrible", "thread", "torment", "trickle",
"usually", "vast", "violence", "weave", "acid", "agony", "ashamed", "awe",
"belly", "blend", "blush", "character", "cheat", "common", "company",
"coward", "creak", "danger", "deadly", "defense", "define", "depend",
"desperate", "destination", "dew", "duck", "dusty", "embarrass", "engine",
"example", "explore", "foe", "freely", "frustrate", "generation", "glove",
"guilty", "health", "hurry", "idiot", "impossible", "inhale", "jaw",
"kingdom", "mention", "mist", "moan", "mumble", "mutter", "observe", "ode",
"pathetic", "pattern", "pie", "prefer", "puff", "rape", "rare", "revenge",
"rude", "scrape", "spiral", "squeeze", "strain", "sunset", "suspend",
"sympathy", "thigh", "throne", "total", "unseen", "weapon", "weary"
};
*/

#endif /* WORDLIST_H_ */
